import Footer from '@/components/modules/Footer/Footer'
import Navigation from '@/components/modules/Navigation/Navigation'
import Categories from '@/components/templates/category/Categories/Categories'
import React from 'react'
import type { Metadata } from "next";

 export const metadata: Metadata = {
  title: "ShopHub | Category",
  description: "Generated by create next app",
};

interface ProductCategory{
  params:{
    slug:string
  }
}

const page:React.FC<ProductCategory> = ({params})=>{
  const {slug} = params
  return (
    <div className="min-h-screen bg-white">
        <Navigation/>
        <Categories slug={slug}/>
        <Footer/>
    </div>
  )
}

export default page