import Footer from '@/components/modules/Footer/Footer'
import Navigation from '@/components/modules/Navigation/Navigation'
import Categories from '@/components/templates/category/Categories/Categories'
import React from 'react'
import type { Metadata } from "next";

 export const metadata: Metadata = {
  title: "ShopHub | Category",
  description: "Generated by create next app",
};


const page:React.FC = ()=>{
  return (
    <div className="min-h-screen bg-white">
        <Navigation/>
        <Categories/>
        <Footer/>
    </div>
  )
}

export default page