import React from 'react';
import type { Metadata } from "next";
import Navigation from '@/components/modules/Navigation/Navigation';
import Footer from '@/components/modules/Footer/Footer';
import ContentAbout from '@/components/templates/about/ContentAbout';

 export const metadata: Metadata = {
  title: "ShopHub | About Us",
  description: "Generated by create next app",
};

const page:React.FC = ()=>{
  return (
    <div className="min-h-screen px-4 bg-white">
        <Navigation/>
        <ContentAbout/>
        <Footer/>
    </div>
  )
}

export default page