import AdminLayout from '@/components/layout/AdminLayout';
import React from 'react';
import type { Metadata } from "next";
import UsersHeader from '@/components/templates/admin/users/UsersHeader/UsersHeader';
import UsersStats from '@/components/templates/admin/users/UsersStats/UsersStats';
import UserList from '@/components/templates/admin/users/UserList/UserList';


export const metadata: Metadata = {
  title: "ShopHub | Admin",
  description: "Generated by create next app",
};

const page:React.FC  = ()=>{
  return (
    <AdminLayout>
        <UsersHeader/>
        <UsersStats/>
        <UserList/>
    </AdminLayout>
  )
}

export default page