import AdminLayout from '@/components/layout/AdminLayout';
import React from 'react';
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "ShopHub | Admin",
  description: "Generated by create next app",
};

const page:React.FC  = ()=>{
  return (
    <AdminLayout>
        this users page admin
    </AdminLayout>
  )
}

export default page