import Footer from '@/components/modules/Footer/Footer'
import Navigation from '@/components/modules/Navigation/Navigation'
import LoginOrRegister from '@/components/templates/auth/LoginOrRegister/LoginOrRegister'
import React from 'react'
import type { Metadata } from "next";

 export const metadata: Metadata = {
  title: "ShopHub | Login-Register",
  description: "Generated by create next app",
};

const page:React.FC = ()=>{
  return (
    <div className="min-h-screen bg-white bg-gradient-to-br from-white via-white to-primary/5 p-4">
        <LoginOrRegister/>
    </div>
  )
}

export default page