import React from 'react'
import type { Metadata } from "next";
import Navigation from '@/components/modules/Navigation/Navigation';
import Footer from '@/components/modules/Footer/Footer';


 export const metadata: Metadata = {
  title: "ShopHub | Contact",
  description: "Generated by create next app",
};

const page:React.FC = ()=>{
  return (
    <div className="min-h-screen px-4 bg-white">
        <Navigation/>
        this is page contact
        <Footer/>
    </div>
  )
}

export default page