import React from 'react'
import type { Metadata } from "next";
import AdminLayout from '@/components/layout/AdminLayout';


export const metadata: Metadata = {
  title: "ShopHub | Admin-Products",
  description: "Generated by create next app",
};

function page() {
  return (
    <AdminLayout>
        this is admin - products
    </AdminLayout>
  )
}

export default page