import React from 'react'
import type { Metadata } from "next";
import AdminLayout from '@/components/layout/AdminLayout';
import ProductsHeader from '@/components/templates/admin/products/ProductsHeader/ProductsHeader';
import ProductsStats from '@/components/templates/admin/products/ProductsStats/ProductsStats';


export const metadata: Metadata = {
  title: "ShopHub | Admin-Products",
  description: "Generated by create next app",
};

function page() {
  return (
    <AdminLayout>
        <ProductsHeader/>
        <ProductsStats/>
    </AdminLayout>
  )
}

export default page