import React from 'react'
import type { Metadata } from "next";
import AdminLayout from '@/components/layout/AdminLayout';


export const metadata: Metadata = {
  title: "ShopHub | Admin",
  description: "Generated by create next app",
};

const page:React.FC = ()=>{
  return (
    <AdminLayout>
        this orders admin 
    </AdminLayout>
  )
}

export default page