import React from 'react'
import type { Metadata } from "next";
import AdminLayout from '@/components/layout/AdminLayout';
import OrdersHeader from '@/components/templates/admin/orders/OrdersHeader/OrdersHeader';
import OrdersStats from '@/components/templates/admin/orders/OrdersStats/OrdersStats';


export const metadata: Metadata = {
  title: "ShopHub | Admin",
  description: "Generated by create next app",
};

const page:React.FC = ()=>{
  return (
    <AdminLayout>
        <OrdersHeader/>
        <OrdersStats/>
        this orders admin 
    </AdminLayout>
  )
}

export default page