import React from 'react'
import type { Metadata } from "next";
import AdminLayout from '@/components/layout/AdminLayout';
import DashboardHeader from '@/components/templates/admin/dashboard/DashboardHeader/DashboardHeader';
import DashboardStats from '@/components/templates/admin/dashboard/DashboardStats/DashboardStats';
import DashboardOrders from '@/components/templates/admin/dashboard/DashboardOrders/DashboardOrders';
import DashboardProducts from '@/components/templates/admin/dashboard/DashboardProducts/DashboardProducts';
import DashboardActions from '@/components/templates/admin/dashboard/DashboardActions/DashboardActions';

export const metadata: Metadata = {
  title: "ShopHub | Admin",
  description: "Generated by create next app",
};

const page:React.FC = ()=>{
  return (
    <AdminLayout>
      <DashboardHeader/>
      <DashboardStats/>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
        <DashboardOrders/>
        <DashboardProducts/>
      </div>
      <DashboardActions/>
    </AdminLayout>
  )
}

export default page