import Navigation from "@/components/modules/Navigation/Navigation";
import React from 'react';
import type { Metadata } from "next";

 export const metadata: Metadata = {
  title: "ShopHub | Products",
  description: "Generated by create next app",
};

const page:React.FC = ()=>{
  return (
    <div className="min-h-screen bg-white">
        <Navigation/>
        products -page
    </div>
  )
}

export default page