import React from 'react';
import type { Metadata } from "next";
import Navigation from '@/components/modules/Navigation/Navigation';
import ProfileHeader from '@/components/templates/profile/ProfileHeader/ProfileHeader';
import ProfileTabs from '@/components/templates/profile/ProfileTabs/ProfileTabs';
import ProfileLayout from '@/components/layout/ProfileLayout';


export const metadata: Metadata = {
  title: "ShopHub | Profile",
  description: "Generated by create next app",
};

const page:React.FC = ()=>{
  return (
    <ProfileLayout>
      <ProfileHeader/>
      <ProfileTabs/>
    </ProfileLayout>
  )
}

export default page