import React from 'react';
import type { Metadata } from "next";
import Navigation from '@/components/modules/Navigation/Navigation';


export const metadata: Metadata = {
  title: "ShopHub | Profile",
  description: "Generated by create next app",
};

const page:React.FC = ()=>{
  return (
    <div className="min-h-screen bg-white">
        <Navigation/>
        this is profile user
    </div>
  )
}

export default page